import { useId, useRef, useState } from 'react';
import { Users, UserPlus, Upload, FileJson, Check, X, LoaderCircle, CircleAlert, Plus } from 'lucide-react';
import type { FileUploadState, ListKind } from '../types/instagram';
interface Props { kind: ListKind; state: FileUploadState; onAdd: (files: FileList | File[]) => void; onRemove: (id: string) => void }
export function FileUploadCard({ kind, state, onAdd, onRemove }: Props) {
  const id = useId(), input = useRef<HTMLInputElement>(null), dragDepth = useRef(0);
  const [dragging, setDragging] = useState(false);
  const followers = kind === 'followers', label = followers ? 'Followers' : 'Following', Icon = followers ? Users : UserPlus;
  const fileSize = (bytes: number) => bytes < 1024 ? `${bytes} B` : bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
  return <section className={`upload-card ${followers ? 'violet' : 'pink'} ${dragging ? 'is-dragging' : ''}`} aria-labelledby={`${id}-title`} onDragEnter={e => { e.preventDefault(); dragDepth.current++; setDragging(true); }} onDragOver={e => e.preventDefault()} onDragLeave={e => { e.preventDefault(); if (--dragDepth.current <= 0) { dragDepth.current = 0; setDragging(false); } }} onDrop={e => { e.preventDefault(); dragDepth.current = 0; setDragging(false); onAdd(e.dataTransfer.files); }}>
    <div className="card-heading"><span className="card-icon"><Icon size={22}/></span><span className="file-type">.JSON</span></div>
    <h2 id={`${id}-title`}>{label}</h2><p className="card-description">{followers ? 'Upload all follower files from your Instagram export.' : 'Upload the following file from your Instagram export.'}</p>
    <input ref={input} id={id} className="sr-only" type="file" accept=".json,application/json" multiple aria-label={`Upload ${kind} files`} tabIndex={-1} onChange={e => { if (e.target.files) onAdd(e.target.files); e.target.value = ''; }}/>
    <button className="drop-zone" onClick={() => input.current?.click()} aria-label={`Choose ${kind} files`}><span className="upload-symbol">{state.ready ? <Check size={23}/> : <Upload size={23}/>}</span><strong>{dragging ? 'Drop your JSON files here' : state.files.length ? 'Add or replace files' : `Upload your ${kind} files`}</strong><span>Drag & drop or <span className="browse-link">browse files</span></span><small>{followers ? 'Multiple files supported' : 'Usually one following.json file'} <span>·</span> 25 MB per file</small></button>
    <div aria-live="polite" className="file-list">{state.files.map(file => <div className={`file-item ${file.status}`} key={file.id}><FileJson size={18}/><div className="file-detail"><span className="file-name" title={file.name}>{file.name}</span><small>{fileSize(file.size)}{file.status === 'valid' && ` · ${file.result!.accounts.length.toLocaleString()} accounts`}{file.status === 'parsing' && ' · Reading locally…'}</small>{file.error && <p className="file-error">{file.error}</p>}{!!file.result?.ignored && <p className="file-warning">Skipped {file.result.ignored} unreadable record(s). Check the completeness of this export.</p>}</div>{file.status === 'parsing' ? <LoaderCircle className="spin" size={16}/> : file.status === 'valid' ? <Check size={16}/> : <CircleAlert size={16}/>}<button className="icon-button" aria-label={`Remove ${file.name}`} onClick={() => onRemove(file.id)}><X size={16}/></button></div>)}</div>
    <div className="card-hint">{state.ready ? <><Check size={14}/>{state.accounts.length.toLocaleString()} unique accounts ready</> : <><FileJson size={14}/><span>{followers ? 'followers_1.json, followers_2.json, …' : 'following.json'}</span></>}{state.files.length > 0 && <button className="add-file" aria-label={`Add more ${kind} files`} onClick={() => input.current?.click()}><Plus size={15}/></button>}</div>
  </section>;
}
