import { useEffect, useMemo, useState } from 'react';
import { Search, ArrowDownAZ, Copy, ExternalLink, CheckCheck, ChevronLeft, ChevronRight } from 'lucide-react';
import type { Account } from '../types/instagram';
const PAGE_SIZE = 100;
export function UserList({ accounts, description, empty, notify }: { accounts: Account[]; description: string; empty: string; notify: (message: string) => void }) {
  const [query, setQuery] = useState(''), [sort, setSort] = useState('az'), [page, setPage] = useState(0);
  const filtered = useMemo(() => { const search = query.trim().replace(/^@/, '').toLowerCase(); return accounts.filter(a => a.username.includes(search)).sort((a, b) => (sort === 'az' ? 1 : -1) * a.username.localeCompare(b.username, 'en')); }, [accounts, query, sort]);
  useEffect(() => { setPage(0); }, [query, sort, accounts]);
  const maxPage = Math.max(0, Math.ceil(filtered.length / PAGE_SIZE) - 1), safePage = Math.min(page, maxPage), visible = filtered.slice(safePage * PAGE_SIZE, (safePage + 1) * PAGE_SIZE);
  async function copy(account: Account) { try { await navigator.clipboard.writeText(account.displayName); notify(`Copied @${account.displayName}`); } catch { notify('Could not access your clipboard. Select the username to copy it.'); } }
  return <><div className="list-intro"><p>{description}</p><span>{filtered.length.toLocaleString()} accounts</span></div><div className="list-controls"><label className="search-field"><Search size={18}/><input aria-label="Search usernames" placeholder="Search usernames…" value={query} onChange={e => setQuery(e.target.value)}/>{query && <button aria-label="Clear search" onClick={() => setQuery('')}>×</button>}</label><label className="sort-control"><ArrowDownAZ size={18}/><select aria-label="Sort usernames" value={sort} onChange={e => setSort(e.target.value)}><option value="az">A–Z</option><option value="za">Z–A</option></select></label></div><div className="user-scroll" key={`${safePage}-${sort}`} tabIndex={0} aria-label="Scrollable account list">{visible.length ? <ul className="users">{visible.map(account => <li key={account.username}><span className={`avatar tone-${account.username.charCodeAt(0) % 4}`} aria-hidden="true">{account.displayName[0].toUpperCase()}</span><span className="username">@{account.displayName}</span><button className="icon-button" aria-label={`Copy ${account.displayName}`} onClick={() => void copy(account)}><Copy size={17}/></button><a className="icon-button" aria-label={`Open ${account.displayName} on Instagram (new tab)`} href={`https://www.instagram.com/${encodeURIComponent(account.username)}/`} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer"><ExternalLink size={17}/></a></li>)}</ul> : <div className="empty-state"><CheckCheck size={30}/><h3>{query ? 'No matching usernames' : empty}</h3><p>{query ? 'Try another name or clear your search.' : 'This reflects only the files you uploaded.'}</p></div>}</div><div className="list-bottom"><span>{filtered.length ? `${safePage * PAGE_SIZE + 1}–${Math.min((safePage + 1) * PAGE_SIZE, filtered.length)} of ${filtered.length.toLocaleString()}` : '0 accounts'}</span><span className="pagination"><button className="icon-button" aria-label="Previous page" disabled={safePage === 0} onClick={() => setPage(p => p - 1)}><ChevronLeft size={18}/></button><span>Page {safePage + 1} of {maxPage + 1}</span><button className="icon-button" aria-label="Next page" disabled={safePage === maxPage} onClick={() => setPage(p => p + 1)}><ChevronRight size={18}/></button></span></div></>;
}
